### PR TITLE
fix(event): on[upper]* for event name syntax

### LINKED ISSUE #30: Ensure event bindings use on[uppercaseChar]* for event name syntax
This means that if you do something like `<div once={} />` it doesn't bind a listener for an event name of `ce`.

### PR DESCRIPTION
**Pull request by stevemao**
BREAKING CHANGE: all small letter like `onevent` is not supported anymore. In react this is ambiguous. React is using camelCase for event names.

Fixes #30

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ export default function (CustomElement, opts) {
           return;
         }
 
-        if (name.indexOf('on') === 0) {
+        if (name.indexOf('on') === 0 && name[2] === name[2].toUpperCase()) {
           syncEvent(node, name.substring(2), props[name]);
```
Comment (treshugart) [inline src/index.js]: Do you need to make sure the first character of the event name is lowercased here?

Comment (stevemao) [inline src/index.js]: isn't `name[2] === name[2].toUpperCase()` checking it?

Comment (treshugart) [inline src/index.js]: That's checking it, but the code below that would be binding `Click` instead of `click`.

Comment (stevemao) [inline src/index.js]: In my earlier PR, https://github.com/webcomponents/react-integration/pull/34/files#diff-1fdf421c05c1140f6d71444ea2b27638L10 is converting the first letter to lower case.

Comment (treshugart) [inline src/index.js]: Ahh yep, see that now. Thanks!

**Comment by treshugart** [comment]
lgtm
